<?php

/**
 * @file
 * Heisencache administrative module.
 *
 * @copyright (c) 2013-2021 Ouest Systèmes Informatiques (OSInet).
 *
 * @license General Public License version 2 or later
 */

declare(strict_types=1);

/**
 * Implements hook_menu().
 */
function heisencache_menu(): array {
  $items = [];
  $items['admin/reports/heisencache'] = [
    'title' => 'Heisencache',
    'access arguments' => ['administer site configuration'],
    'page callback' => 'heisencache_page_reports',
    'file' => 'heisencache.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_views_api().
 */
function heisencache_views_api(): array {
  $path = drupal_get_path('module', 'heisencache');
  return [
    'api' => "3",
    'path' => "$path/views",
    'template path' => "$path/themes",
  ];
}
