<?php
/**
 * @file
 * Heisencache module.
 *
 * @author: Frederic G. MARAND <fgm@osinet.fr>
 *
 * @copyright (c) 2013-2017 Ouest Systèmes Informatiques (OSInet).
 *
 * @license General Public License version 2 or later
 */

use Drupal\heisencache\HeisencacheServiceProvider as H;
use League\CommonMark\CommonMarkConverter;

/**
 * Implements hook_help().
 */
function heisencache_help($route_name) {
  switch ($route_name) {
    case 'help.page.heisencache':
      // Hook_requirements() will have prevented module enabling if the library
      // was not already present, so there is no need to check for its presence.
      $converter = new CommonMarkConverter();
      $markdown = file_get_contents(__DIR__ . '/README.md');
      $html = $converter->convertToHtml($markdown);
      break;

    default:
      $html = NULL;
      break;
  }

  return $html;
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function heisencache_menu_links_discovered_alter(array &$links) {
  \Drupal::service(H::LINKS_PROVIDER)->alterLinks($links);
}
